services:
  - type: web
    name: gn2-0
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -w 4 -k uvicorn.workers.UvicornWorker
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_WEBHOOK_SECRET
        sync: false
